<?php

/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 */

/**
 * @category   Magenerds
 * @package    Magenerds_RichSnippet
 * @subpackage view
 * @copyright  Copyright (c) 2019 TechDivision GmbH (https://www.techdivision.com)
 * @link       https://www.techdivision.com/
 * @author     Belinda Tschampel <b.tschampel@techdivision.com>
 */

/** @var $block \Magenerds\RichSnippet\Block\Schemaorg */

$productJson = '';
$productData = $block->getProductSchema();
if (!empty($productData)) {
    $productJson = json_encode($productData);
}

?>
<?php if ($block->valueIsSet($productJson)): ?>
    <?php
    echo '<script type="application/ld+json">' . $productJson . '</script>'
    ?>
<?php endif; ?>
