<?php
/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 */

/**
 * @category   Magenerds
 * @package    Magenerds_RichSnippet
 * @subpackage view
 * @copyright  Copyright (c) 2019 TechDivision GmbH (http://www.techdivision.com)
 * @link       http://www.techdivision.com/
 * @author     Martin Eisenführer <m.eisenfuehrer@techdivision.com>
 */

/** @var $block \Magenerds\RichSnippet\Block\Schemaorg */

$organizationJson = '';
$organization = $block->getOrganizationSchema();
if (!empty($organization)) {
    $organizationJson = json_encode($organization);
}

?>
<?php if ($block->valueIsSet($organizationJson)): ?>
    <?php
        echo '<script type="application/ld+json">'.$organizationJson.'</script>'
    ?>
<?php endif; ?>