<?php

/** @noinspection PhpDeprecationInspection */

/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 */

use Magenerds\RichSnippet\Block\FacebookOpenGraph;

/**
 * @category   Magenerds
 * @package    Magenerds_RichSnippet
 * @subpackage view
 * @copyright  Copyright (c) 2019 TechDivision GmbH (https://www.techdivision.com)
 * @link       https://www.techdivision.com/
 * @author     Julia Mehringer <j.mehringer@techdivision.com>
 */

/** @var $block FacebookOpenGraph */

$fbAppId = $block->getFacebookAppId();
/** @noinspection PhpUnhandledExceptionInspection */
$ogData = $block->getOpenGraphData()
?>
<?php if ($fbAppId) : ?>
    <meta property="fb:app_id" content="<?php echo $block->escapeQuote($fbAppId); ?>">
<?php endif; ?>

<?php foreach ($ogData as $key => $value): ?>
    <?php if (isset($key)): ?>
        <meta property="og:<?php echo $block->escapeQuote($key); ?>" content="<?php echo $block->escapeQuote($value); ?>">
    <?php endif; ?>
<?php endforeach; ?>
