<?php

/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * https://opensource.org/licenses/osl-3.0.php
 */

use Magenerds\RichSnippet\Block\SchemaOrg;

/**
 * @category   Magenerds
 * @package    Magenerds_RichSnippet
 * @subpackage view
 * @copyright  Copyright (c) 2019 TechDivision GmbH (https://www.techdivision.com)
 * @link       https://www.techdivision.com/
 * @author     Belinda Tschampel <b.tschampel@techdivision.com>
 */

/** @var $block SchemaOrg */

/** @noinspection PhpUnhandledExceptionInspection */
if (($schema = $block->getSchema())) {
    echo '<script type="application/ld+json">' . json_encode($schema) . '</script>';
}
if (($schemaBreadcrumb = $block->getSchemaBreadcrumb())) {
    echo '<script type="application/ld+json">' . json_encode($schemaBreadcrumb) . '</script>';
}
